### PR TITLE
Fixed method call in templates/driver.groovy

### PR DESCRIPTION
**Pull request by dsteelma-umd**
The driver.groovy file was calling "eachRecordFromStream" method
on JsonStreamReader, when actual method is named "eachRecordInStream".

This was leading to an exception similar to the following when using
"gradle run":

```
Exception in thread "main" groovy.lang.MissingMethodException: No signature of method: org.kuali.ole.contrib.json.JsonStreamReader.eachRecordFromStream() is applicable for argument types: (null, driver$_run_closure1) values: [null, driver$_run_closure1@3e7d5a1b]
        at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:56)
        at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:51)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:120)
        at driver.run(driver.groovy:33)
        at groovy.lang.GroovyShell.runScriptOrMainOrTestOrRunnable(GroovyShell.java:258)
        at groovy.lang.GroovyShell.run(GroovyShell.java:221)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSite.invoke(PogoMetaMethodSite.java:166)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.call(PogoMetaMethodSite.java:68)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
        at org.kuali.ole.contrib.main.Main.main(Main.groovy:31)
```

### CODE REVIEW

**Comment by adjam** [comment]
Can you tell I didn't test it that much? =P  Thanks!

**Comment by dsteelma-umd** [comment]
Adam,

Well, you did say "no warranties"... It is nice to see some of the tools other folks are working with. And I do appreciate the "updateOLESequences.groovy" script -- I'm definitely going to be using that until something "official" gets put into OLE to fix the problem once and for all.

There are two other changes that are needed to make the "gradle run" command work out-of-the-box, that I'm not sure how to put into a pull request:

1) Oracle's ojdbc7-12.1.0.1.jar is not available in public Maven repositories, so "gradle run" fails with:

FAILURE: Build failed with an exception.
- What went wrong:
  Execution failed for task ':migration:run'.
  > Could not resolve all dependencies for configuration ':migration:runtime'.
  > Could not find com.oracle:ojdbc7:12.1.0.1.
   Searched in the following locations:
       file:/home/vagrant/.m2/repository/com/oracle/ojdbc7/12.1.0.1/ojdbc7-12.1.0.1.pom
       file:/home/vagrant/.m2/repository/com/oracle/ojdbc7/12.1.0.1/ojdbc7-12.1.0.1.jar
       https://repo1.maven.org/maven2/com/oracle/ojdbc7/12.1.0.1/ojdbc7-12.1.0.1.pom
       https://repo1.maven.org/maven2/com/oracle/ojdbc7/12.1.0.1/ojdbc7-12.1.0.1.jar
   Required by:
       org.kuali.ole.contrib:migration:1.0-SNAPSHOT

I've been working around this either by commenting out the dependency (line 57 in the templates/build.gradle file), or downloading the jar from Oracle at http://www.oracle.com/technetwork/database/features/jdbc/jdbc-drivers-12c-download-1958347.html and inserting into the .m2 directory by hand.

Since it is not needed by the example driver.groovy file, I could see either commenting out, or putting a note in the README.md about the dependency.

2) The "data.json" file is needed somewhere on the classpath. Otherwise "gradle run" fails with:

Exception in thread "main" groovy.lang.GroovyRuntimeException: Ambiguous method overloading for method com.fasterxml.jackson.core.JsonFactory#createParser.
Cannot resolve which method to invoke for [null] due to overlapping prototypes between:
[class [B]
[class [C]
[class java.io.File]
[class java.io.InputStream]
[class java.io.Reader]
[class java.lang.String]
[class java.net.URL]
at groovy.lang.MetaClassImpl.chooseMostSpecificParams(MetaClassImpl.java:3202)
       ...
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:120)
at driver.run(driver.groovy:33)
at groovy.lang.GroovyShell.runScriptOrMainOrTestOrRunnable(GroovyShell.java:258)
        ...

I "fixed" this by copying the templates/src/test/resource/data.json to migration/build/classes/main/ after running "gradle run" at least once (the migration/build/ directory doesn't exist until then).

Thanks for the efforts!

David

**Comment by adjam** [comment]
It is not possible to ship the oracle libraries due to licensing issues.  Unfortunately I _do_ have them installed so I missed that I hadn't commented out that reference.  If you're not using Oracle anywhere, just `//` out that line.

**Comment by adjam** [comment]
Alternately, if you _are_ using Oracle and you need to have the jars available, since the gradle build does reference local Maven repositories (which you'll be using anyhow if you're building OLE), the following should work for you, if you have the Oracle driver jar in hand:

`mvn install:install-file -DgroupId=com.oracle -DartifactId=ojdbc7 -Dversion=[version number here] -Dpackaging=jar -Dfile=[path to downloaded  jar]`

This stashes the driver in the right place along with the minimal metadata needed to avoid Maven complaints about missing POMs, etc.

**Comment by dsteelma-umd** [comment]
Adam,

Yes, I'm experienced the same problem with the ODBC jar in OLE, so I understand the licensing issues. I guess I was thinking that since the jar isn't actually needed to make the sample "driver.groovy" script work, that either the dependency should be commented out by default (like you have for the mariadb drivers), or mention something about it in the README.md file (perhaps in the "Requirements" section) so people will know they need to get it.

Thanks again,

David

**Comment by adjam** [comment]
That's what I did.  You can pull down the latest commit to get that fix, I'm also trying to make sure the 'default' driver.groovy Just Works.

**Pull request merged**
